#!/bin/sh

tmp=/tmp/finnish-weather-wp-plugin

(
	rm -rf $tmp
	mkdir $tmp
	cp -a * $tmp/
	cd $tmp
	VERSION=$(grep Versio finnish-weather-wp-plugin.php | awk '{print $2 }')
	rm -f __*
	cd php
	rm -f finnish_*.json
	cd ..
	cd ..
	rm -f finnish-weather-wp-plugin.*.zip
	zip -r finnish-weather-wp-plugin.$VERSION.zip finnish-weather-wp-plugin
	cp  finnish-weather-wp-plugin.*.zip ~www-data/html/wp/finnish-weather-wp-plugin/ -v
)

echo $tmp.zip done.
