#!/bin/sh
cntmax=160

doinst()
{
	cnt=$(( $cnt + 1 ))
	echo "Installing $1 ($cnt/$cntmax) ...."
	pip3 install --user $1
}

doinst acme
doinst apt-clone
doinst apturl
doinst argon2-cffi
doinst async-generator
doinst attrs
doinst backcall
doinst bcrypt
doinst bleach
doinst blinker
doinst Brlapi
doinst browser-cookie3
doinst certbot
doinst certifi
doinst cffi
doinst chardet
doinst Click
doinst colorama
doinst command-not-found
doinst ConfigArgParse
doinst configobj
doinst configparser
doinst cryptography
doinst cupshelpers
doinst dblatex
doinst dbus-python
doinst decorator
doinst defer
doinst defusedxml
doinst devscripts
doinst distro
doinst distro-info
doinst dnspython
doinst duplicity
doinst entrypoints
doinst fasteners
doinst fmiopendata
doinst future
doinst geojson
doinst gmaps
doinst gpg
doinst httplib2
doinst idna
doinst ipykernel
doinst ipython
doinst ipython-genutils
doinst ipywidgets
doinst isc
doinst jedi
doinst Jinja2
doinst josepy
doinst jsonschema
doinst jupyter-client
doinst jupyter-core
doinst jupyterlab-pygments
doinst jupyterlab-widgets
doinst keyring
doinst language-selector
doinst launchpadlib
doinst lazr.restfulclient
doinst lazr.uri
doinst lockfile
doinst louis
doinst lz4
doinst macaroonbakery
doinst Mako
doinst Markdown
doinst MarkupSafe
doinst matplotlib-inline
doinst mistune
doinst mock
doinst monotonic
doinst mysql
doinst mysql-connector-python
doinst mysqlclient
doinst nbclient
doinst nbconvert
doinst nbformat
doinst nest-asyncio
doinst netifaces
doinst notebook
doinst numpy
doinst oauthlib
doinst olefile
doinst packaging
doinst PAM
doinst pandocfilters
doinst paramiko
doinst parsedatetime
doinst parso
doinst pbkdf2
doinst pbr
doinst pexpect
doinst phue
doinst pickleshare
doinst Pillow
doinst pip
doinst ply
doinst prometheus-client
doinst prompt-toolkit
doinst protobuf
doinst ptyprocess
doinst py-mysql
doinst pyaes
doinst pycairo
doinst pycparser
doinst pycrypto
doinst pycryptodome
doinst pycups
doinst Pygments
doinst PyGObject
doinst PyICU
doinst PyJWT
doinst pymacaroons
doinst PyNaCl
doinst pyOpenSSL
doinst pyparsing
doinst pyRFC3339
doinst pyrsistent
doinst python-apt
doinst python-dateutil
doinst python-debian
doinst python-magic
doinst pytz
doinst pyxdg
doinst PyYAML
doinst pyzmq
doinst reportlab
doinst requests
doinst requests-toolbelt
doinst requests-unixsocket
doinst SecretStorage
doinst Send2Trash
doinst setuptools
doinst simplejson
doinst six
doinst ssh-import-id
doinst systemd-python
doinst terminado
doinst testpath
doinst tornado
doinst traitlets
doinst ubuntu-advantage-tools
doinst ubuntu-drivers-common
doinst ufw
doinst unattended-upgrades
doinst unidiff
doinst urllib3
doinst usb-creator
doinst wadllib
doinst wcwidth
doinst webencodings
doinst wheel
doinst widgetsnbextension
doinst xkit
doinst xlrd
doinst zope.component
doinst zope.event
doinst zope.hookable
doinst zope.interface
